services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smarthaven
      MYSQL_USER: smarthaven
      MYSQL_PASSWORD: smarthaven
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_polish_ci
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3306:3306
    networks:
      - smarthaven-docker
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.htaccess:/var/www/html/.htaccess
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - smarthaven-docker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - smarthaven-docker
#  node-server:
#    image: node:20
#    container_name: node-server
#    working_dir: /DeviceSimulators
#    volumes:
#      - ./DeviceSimulators:/DeviceSimulators
#    command: "node app.js"
#    ports:
#      - "3000:3000"
networks:
  smarthaven-docker:
    driver: bridge